# Generated by Django 4.0.2 on 2022-05-30 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points', '0002_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='user_credits', to=settings.AUTH_USER_MODEL),
        ),
    ]
