# Generated by Django 4.0.2 on 2022-05-31 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_options'),
        ('movies', '0009_schedule'),
        ('points', '0004_transaction_transactiondetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('totalcredit', models.IntegerField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('qrImage', models.ImageField(blank=True, max_length=255, null=True, upload_to='qrticket/')),
                ('branch_ticket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='branch.branch')),
                ('credits_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='points.credits')),
                ('schedule_ticket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies.schedule')),
            ],
        ),
    ]
