# Generated by Django 4.0.2 on 2022-05-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0007_alter_ticket_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='name_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
