# Generated by Django 4.0.2 on 2022-05-31 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_schedule_date_schedule_and_more'),
        ('points', '0008_alter_ticket_name_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='schedule_ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='timetable_ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='movies.timetable'),
            preserve_default=False,
        ),
    ]
