# Generated by Django 4.0.2 on 2022-05-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0009_remove_ticket_schedule_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_functions',
            field=models.DateField(default='2022-05-31'),
            preserve_default=False,
        ),
    ]
