# Generated by Django 4.0.2 on 2022-05-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0010_ticket_date_functions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
