# Generated by Django 4.0.2 on 2022-06-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0011_ticket_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='name_award',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
