# Generated by Django 4.0.2 on 2022-06-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0012_alter_awards_name_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='time_transaction',
            field=models.TimeField(auto_now_add=True, default='19:35'),
            preserve_default=False,
        ),
    ]
