# Generated by Django 4.0.2 on 2022-09-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_alter_branch_address_branch_alter_branch_name_branch_and_more'),
        ('points', '0013_transaction_time_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='branch_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_functions',
            field=models.DateField(blank=True, null=True),
        ),
    ]
