from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from movies.api import serializable
from movies import models
from movies.api.view.actors import Actors
from movies.api.view.categories import Categories
from movies.api.view.movie import Movies,NextPremiere,bestMovie,bestMovie5   
from movies.api.view.schedule import ScheduleList,ScheduleCreate,Billboard
from movies.api.view.timetable import TimetableList,TimetableCreate
