# Generated by Django 4.0.2 on 2022-08-16 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from user.newRols import NewRols
from user.newAdmin import newAdmin

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0003_alter_branch_address_branch_alter_branch_name_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    
    def initial_data(apps, schema_editor):
        NewRols()
        newAdmin()

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='users/')),
                ('qrprofile', models.ImageField(blank=True, null=True, upload_to='qr/')),
                ('type', models.CharField(max_length=1)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('ci', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cedula Identificacion')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('branch_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='branch.branch')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='user.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(initial_data),
    ]
