# Generated by Django 4.0.2 on 2022-06-21 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0014_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='Survey_template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(auto_now_add=True)),
                ('date_final', models.DateField(blank=True, null=True)),
                ('state', models.IntegerField(default=1)),
                ('question1', models.CharField(max_length=255)),
                ('question2', models.CharField(max_length=255)),
                ('question3', models.CharField(max_length=255)),
                ('question4', models.CharField(max_length=255)),
                ('question5', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=255)),
                ('question2', models.CharField(max_length=255)),
                ('question3', models.CharField(max_length=255)),
                ('question4', models.CharField(max_length=255)),
                ('question5', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('answer1', models.CharField(blank=True, max_length=100, null=True)),
                ('answer2', models.CharField(blank=True, max_length=100, null=True)),
                ('answer3', models.CharField(blank=True, max_length=100, null=True)),
                ('answer4', models.CharField(blank=True, max_length=100, null=True)),
                ('answer5', models.CharField(blank=True, max_length=100, null=True)),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies.movies')),
                ('suervey_template', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='survey.survey_template')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
            },
        ),
    ]
