# Generated by Django 4.0.2 on 2022-06-27 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branch', '0003_alter_branch_address_branch_alter_branch_name_branch_and_more'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='branch.branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
