# Generated by Django 4.0.2 on 2022-07-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_survey_branch_alter_survey_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_template',
            name='name',
            field=models.CharField(default='Que tal te fue?', max_length=100),
            preserve_default=False,
        ),
    ]
