# Generated by Django 4.0.2 on 2022-07-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_survey_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='answer1',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='answer2',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='answer3',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='answer4',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
