# Generated by Django 4.0.2 on 2022-08-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_survey_status_alter_survey_answer1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='answer5',
            field=models.CharField(default='', max_length=100),
        ),
    ]
