# Generated by Django 4.0.2 on 2022-05-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    def insert_init_data(apps,schema_editor):
        categories=["Acción","Aventuras","Ciencia Ficción","Comedia","Documental","Drama","Fantasía","Musical","Suspenso","Terror","Animación"]
        Category=apps.get_model('movies','categories')
        for cs in categories:
            print(cs)
            Category.objects.create(category_name=cs)
    operations = [
        migrations.CreateModel(
            name='actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_actor', models.CharField(max_length=255)),
                ('photo_actor', models.ImageField(max_length=255, upload_to='actors/')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
            },
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.RunPython(insert_init_data)
    ]
