# Generated by Django 4.0.2 on 2022-05-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_movie', models.CharField(max_length=255, unique=True)),
                ('description_movie', models.TextField(max_length=255)),
                ('duration_movie', models.TimeField()),
                ('premiere_date_movie', models.DateField()),
                ('departure_date_movie', models.DateField()),
                ('photo_movie', models.ImageField(max_length=255, upload_to='movies/')),
                ('actor_movie', models.ManyToManyField(to='movies.actors')),
                ('category_movie', models.ManyToManyField(to='movies.categories')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
