# Generated by Django 4.0.2 on 2022-05-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='photo_actor',
            field=models.ImageField(max_length=255, upload_to='media/actors/'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='photo_movie',
            field=models.ImageField(max_length=255, upload_to='media/movies/'),
        ),
    ]
