# Generated by Django 4.0.2 on 2022-05-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_actors_photo_actor_alter_movies_photo_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='photo_actor',
            field=models.ImageField(max_length=255, upload_to='actors/'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='photo_movie',
            field=models.ImageField(max_length=255, upload_to='movies/'),
        ),
    ]
