# Generated by Django 4.0.2 on 2022-05-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_actors_photo_actor_alter_movies_photo_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='duration_movie',
            field=models.DurationField(),
        ),
    ]
