# Generated by Django 4.0.2 on 2022-05-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_categories_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='actor_movie',
            field=models.ManyToManyField(related_name='actor_movie', to='movies.actors'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='category_movie',
            field=models.ManyToManyField(related_name='category_movie', to='movies.categories'),
        ),
    ]
