# Generated by Django 4.0.2 on 2022-05-31 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_options'),
        ('movies', '0008_alter_movies_actor_movie_alter_movies_category_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_schedule', models.DateField()),
                ('time_schedule', models.TimeField()),
                ('branch_schedule', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='branch.branch')),
                ('movies_schedule', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies.movies')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
