# Generated by Django 4.0.2 on 2022-05-31 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date_schedule',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time_schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_timetable', models.DateField()),
                ('hour_timetable', models.TimeField()),
                ('schedule_timetable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies.schedule')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
            },
        ),
    ]
