# Generated by Django 4.0.2 on 2022-06-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_schedule_date_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='room',
        ),
    ]
