# Generated by Django 4.0.2 on 2022-06-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_remove_schedule_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='room',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
