# Generated by Django 4.0.2 on 2022-06-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_timetable_room'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('day_timetable', 'hour_timetable', 'room')},
        ),
    ]
