# Generated by Django 4.0.2 on 2022-06-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_alter_branch_address_branch_alter_branch_name_branch_and_more'),
        ('movies', '0013_alter_timetable_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('movies_schedule', 'branch_schedule')},
        ),
    ]
