# Generated by Django 4.0.2 on 2022-07-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day_timetable',
            field=models.DateField(auto_now_add=True),
        ),
    ]
