# Generated by Django 4.0.2 on 2022-07-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_timetable_day_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day_timetable',
            field=models.DateField(),
        ),
    ]
