# Generated by Django 4.0.2 on 2022-05-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_branch', models.CharField(max_length=100)),
                ('address_branch', models.CharField(max_length=100)),
                ('phone_branch', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
