# Generated by Django 4.0.2 on 2022-06-17 08:05

from django.db import migrations, models
from branch.newBranch import NewBranch

class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_options'),
    ]
    
    def init_data(apps, schema_editor):
        NewBranch()

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address_branch',
            field=models.CharField(max_length=100, verbose_name='Dirección de la sucursal'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name_branch',
            field=models.CharField(max_length=100, verbose_name='Nombre de la sucursal'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone_branch',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono de la sucursal'),
        ),
        migrations.RunPython(init_data),
    ]
